<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AB.Ecommerce.Gros.Shared\AB.Ecommerce.Gros.Shared.csproj" />
    <ProjectReference Include="..\AB.Ecommerce.Gros.Business\AB.Ecommerce.Gros.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Repositories\" />
    <None Remove="Microsoft.EntityFrameworkCore" />
    <None Remove="Pomelo.EntityFrameworkCore.MySql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.8" />
  </ItemGroup>
</Project>
