<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entities\" />
    <None Remove="Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AB.Ecommerce.Gros.Shared\AB.Ecommerce.Gros.Shared.csproj" />
  </ItemGroup>
</Project>
